# Generated by Django 4.1.2 on 2022-10-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislation_type', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('file_number', models.IntegerField()),
                ('created', models.DateField()),
                ('final_action', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='LegislationSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legistar.legislation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legistar.person')),
            ],
        ),
    ]
