# Generated by Django 4.1.2 on 2022-10-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("legistar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="legistar_guid",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legislation",
            name="legistar_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="legislation",
            name="file_number",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="LegislationText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_html", models.TextField(null=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "legislation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legistar.legislation",
                    ),
                ),
            ],
        ),
    ]
