# Generated by Django 4.1.2 on 2022-10-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legistar", "0003_rename_legislationsponsors_legislationsponsor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="sponsors",
            field=models.ManyToManyField(to="legistar.person"),
        ),
        migrations.DeleteModel(
            name="LegislationSponsor",
        ),
    ]
