# Generated by Django 4.1.2 on 2022-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legistar", "0005_alter_legislation_file_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislationaction",
            name="action_by",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
