# Generated by Django 5.0 on 2024-02-14 18:04

import autoslug.fields
from django.db import migrations

from django.template.defaultfilters import slugify

def create_slug(apps, schema_editor):
    Person = apps.get_model('legistar', 'Person')
    for person in Person.objects.all():
        person.slug = slugify(person.name)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('legistar', '0006_legislationaction_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.RunPython(create_slug, reverse_code=migrations.RunPython.noop),
    ]
