apiVersion: apps/v1
kind: Deployment
metadata:
  name: phlparty
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: phlparty
  template:
    metadata:
      labels:
        app: phlparty
    spec:
      imagePullSecrets:
      - name: gh-sharph
      containers:
      - image: 'ghcr.io/sharph/phl-party:{{ .Values.image.tag }}'
        name: phlparty
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: username
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: password
        - name: DJANGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: host
        - name: DJANGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: port
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: dbname
        - name: DJANGO_ALLOWED_HOSTS
          value: '["{{ .Values.domain }}"]'
        - name: DJANGO_DEBUG
          value: "false"
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: phlparty-app
              key: django-secret
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
        startupProbe:
          httpGet:
            path: /ht/
            port: 8000
            httpHeaders:
            - name: Host
              value: "{{ .Values.domain }}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8000
            httpHeaders:
            - name: Host
              value: "{{ .Values.domain }}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /ht/
            port: 8000
            httpHeaders:
            - name: Host
              value: "{{ .Values.domain }}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: phlparty
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: phlparty