apiVersion: batch/v1
kind: Job
metadata:
  name: phlparty-db-migration
  labels:
    app: phlparty-db-migration
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    metadata:
      labels:
        app: phlparty-db-migration
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: gh-sharph
      containers:
      - image: 'ghcr.io/sharph/phl-party:{{ .Values.image.tag }}'
        name: phl-party-db-migration
        command: ["./manage.py", "migrate"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: username
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: password
        - name: DJANGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: host
        - name: DJANGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: port
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: dbname
        - name: DJANGO_ALLOWED_HOSTS
          value: '["{{ .Values.domain }}"]'
        - name: DJANGO_DEBUG
          value: "false"
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: phlparty-app
              key: django-secret
        resources:
          limits:
            memory: 512Mi
            cpu: 250m