apiVersion: apps/v1
kind: Deployment
metadata:
  name: phlparty-updater
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: phlparty-updater
  template:
    metadata:
      labels:
        app: phlparty-updater
    spec:
      imagePullSecrets:
      - name: gh-sharph
      containers:
      - image: 'ghcr.io/sharph/phl-party:{{ .Values.updater.image.tag }}'
        name: phlparty
        command: ["./manage.py", "updatefromrss", "--repeat-seconds", "3600"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: username
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: password
        - name: DJANGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: host
        - name: DJANGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: port
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: phlparty-database-app
              key: dbname
        - name: DJANGO_ALLOWED_HOSTS
          value: '["{{ .Values.domain }}"]'
        - name: DJANGO_DEBUG
          value: "false"
        - name: DJANGO_SECRET
          valueFrom:
            secretKeyRef:
              name: phlparty-app
              key: django-secret
        resources:
          limits:
            memory: 512Mi
            cpu: 250m